name: Node.js CI

on: push

jobs:
  build:
    name: Node CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Environment info
      run: |
        docker-compose --version
    - name: Where am i
      run: ls -l
    - name: Docker compose up
      run: cd ./back-end && sudo docker-compose up
