name: Node.js CI

on: push

jobs:
  build:
    name: Node CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Environment info
      run: |
        docker-compose --version

    - name: Docker compose up
      run: cd ./back-end && sudo docker-compose up -d

    - name: Npm install back-end
      run: cd ./back-end && npm install

    - name: Npm start back-end
      run: cd ./back-end && npm run start

    - name: Run back test
      run: cd ./back-end && npm run test
